### ISSUE TITLE
lvl 14 feat 2-wep flurry causes error

### ISSUE THREAD

**Issue by dharkus5000** [reonZ/pf2e-dailies#21]
for the lvl 15 fighter class feature that gives a daily feat (improved flexibility), when two-weapon flurry is selected as the option, an error occurs as follows
`Error: An error occured while trying to create a feat source with uuid: Actor.VbHx1A7XN8e4igK5.Item.vYVucMIBBGRi0iXm
    createFeatSource api.ts:85
process.ts:151:20`
& 
`The error occured during processing of dailies.flexibility process.ts:152:20`
the lvl 9 version, combat flexibility works as expected

**Comment by reonZ** [comment]
![image](https://github.com/reonZ/pf2e-dailies/assets/651462/5b848dc0-0909-4583-acf6-030911fe92e3)

The only reason this error (the first one) would occur is if the module can't find the feat in question, looking at the uuid there, there is definitely something wrong because it points to an actor instead of a compendium or world entry, did you per chance drag & drop the `Two-Weapon Flurry` from an actor instead of using the compendium browser ?

**Comment by reonZ** [comment]
I am guessing this solved your problem.

**Comment by dharkus5000** [comment]
yep, duplicated the PC, then did rest then daily prep, clicked X then added from compendium and it works - weird that the source of the feat would make a difference though

**Comment by reonZ** [comment]
it is not weird, that is how foundry works, and it can work even if the source comes from an actor, but the problem is you probably deleted the feat from the actor after that, so the module is trying to find a source that doesn't exist anymore.
