### ISSUE TITLE
Staves and Domains

### ISSUE THREAD

**Issue by Neakas** [reonZ/pf2e-dailies#56]
Hi! Fantastic Module!

i have one thing that "might" need fixing? So i have a Player who is a Divine Spellcaster and is currently using the Staff of Necromancy:
![grafik](https://github.com/reonZ/pf2e-dailies/assets/6743232/cc070afd-9ddb-46e6-b681-7758ba53e166)

by Raw the Rules say:

![grafik](https://github.com/reonZ/pf2e-dailies/assets/6743232/934e1be0-3fbb-468d-9f85-63752367f06b)

my Divine Spellcaster should be able to Cast all the Spells from the Staff except Grim Tendrils which is

"arcane, ocult" so not on his spelllist

![grafik](https://github.com/reonZ/pf2e-dailies/assets/6743232/0f86eda6-96ea-47a9-b04a-04377c2279cc)

could there be an option to filter that Spell out in the Spell Entry Creation? Maybe i'm missing something or that Question has already been answered...im sorry if so.

**Comment by reonZ** [comment]
the module doesn't handle such thing, it is quite tricky to do because there are always exceptions, such as getting access to other traditions via dedication or the likes of kineticists who can use anything related to the elements they can channel.

Maybe i will find a some way to filter things eventually, but for now, this is gonna have to be on the players for now.

**Comment by Neakas** [comment]
i figured as much, never hurts to ask :)
