### ISSUE TITLE
[Feature Request] Wizard Spell Blending Thesis

### ISSUE THREAD

**Issue by Aziareel** [reonZ/pf2e-dailies#78]
Wizards have access to this Arcane Thesis:

> You theorize that spell slots are a shorthand for an underlying energy that powers all spellcasting, and you've found a way to tinker with the hierarchy of spell slots, combining them to fuel more powerful spells.
During your daily preparations, you can trade two spell slots of the same spell rank for a bonus spell slot of up to 2 spell ranks higher than the traded spell slots. You can exchange as many spell slots as you have available. Bonus spell slots must be of a spell rank you can normally cast, and each bonus spell slot must be of a different spell rank. You can also trade any spell slot for two additional cantrips, though you can't trade more than one spell slot at a time for additional cantrips in this way.

Would it be possible to add this functionality to the module? Like having a drop-down menu for each spell rank with a choice to trade 2 slots for 2 cantrips slots/1 spell rank+1 slot/1 spell rank+2 slot, having the above mentioned restrictions.

Thank you for your work, all your pf2e modules are great.

**Comment by reonZ** [comment]
The issue i can see is that i have no way to revert to the original because the spellcasting data is 100% manual in the system, that alone would make this daily very unreliable. Not to mention how tricky working with the system spellcasting entries is.

I doubt it would work with the module's interface, so i would have to cook something completely new specifically for this feature. Sorry but i will pass.

**Comment by Aziareel** [comment]
It seems you are right about the manual spell entries, that would impose more problems than it might solve.
Thank you regardless.
