### ISSUE TITLE
focus points on animist with circle of spirits

### ISSUE THREAD

**Issue by Peregrin-official** [reonZ/pf2e-dailies#82]
an Animist with the Circle of Spirits feat should get at least 2 focus points, one per attuned spirit, but the automated assigned spells does not account for this, only showing one Focus Point

**Comment by reonZ** [comment]
Focus points are linked to your character, not the spellcasting entry (because you could have multiple focus entries, but they still share one pool), therefore the module doesn't set or increase them, it is 100% handled by the system and the character.

I checked and the feat doesn't have any rule element increasing the character's pool, this is something that should be done by the devs of the system.

**Comment by lholden** [comment]
Hmm. It's a shame that PF2e Dailies won't handle this.

With Circle of Spirits, you *want* both vessel spells added to your list because once per round, you can swap your primary and secondary apparitions. 

![image](https://github.com/user-attachments/assets/f1d1d14f-cca1-48e6-bca9-0ff6b5e77e0d)

If PF2 Dailies doesn't handle this, then you basically need to drag the second vessel spell to the list after every daily preparation. 

Now granted, you are only allowed to *cast* the Vessel spell of your active apparition :)

**Comment by reonZ** [comment]
> Hmm. It's a shame that PF2e Dailies won't handle this.

There is nothing to handle, pool point is done by the system, you just have to:

1/ wait for someone to make the RE for it on the feat
2/ report it yourself in case it was missed

You can go on discord and ask them about it.
