### ISSUE TITLE
Ability to Flag User-Inputted Items?

### ISSUE THREAD

**Issue by skcb64** [reonZ/pf2e-dailies#9]
Hi, first off, this is a fantastic module and it's great seeing it improve so fast!
I'm creating a content module for a third-party class, the Legendary Medium, whose abilities vary significantly from day-to-day. Previously, we were limited on how much automation could be attached to the class, but obviously this module brings a lot of possibility to that.

With core game content I would be happy to figure out the JavaScript myself and submit a pull request, but since this is third-party content for a much smaller user-base, I was wondering what the timeline would look like for allowing users to integrate custom items with this module, or if you have any advice for how I could package that functionality with the items for this class on my own?

**Comment by reonZ** [comment]
Could you give me an example of what you mean by custom content ?

Because all the daily features present in this module require their own code, there is no way to make it customizable.

I could eventually add a way for user to add items that are compatible with already developed features, like let say you create a new feat that grants the ability to be trained in a skill, this feature already exists in the module, so it could be possible to allow you to add your item to the list, but that would be the extent of what is possible.

**Comment by skcb64** [comment]
Ah, sorry if I was unclear. By custom content, in this case I mean class features that grant temporary proficiencies and feats chosen during daily preparations. So the already existing features cover everything I, at least, am interested in. So adding an item to the module's list is exactly what I am suggesting.
And thank you for the clarification on how it functions!

**Comment by reonZ** [comment]
I will see what i can do about it, it was not setup for it but maybe i can tinker something.

**Comment by reonZ** [comment]
The version `2.0.0` is out and fully support homebrew dailies, you should be able to create pretty much anything.

I have also made an extension module which provide a very powerful text editor (the same as VSCode) to help you create  your homebrew dailies.

You can find the extension module here: https://github.com/reonZ/pf2e-dailies-ext
